name: Backend deployment

on:
  push:
    branches: [main]
    paths:
      - "aghub-backend/**"

jobs:
  deploy:
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🚚 Copy entire repo to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: "." # send whole repo
          target: "~/aghub"

      - name: 🚀 Deploy backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            echo "🔧 Backend deployment started"
            cd ~/aghub/aghub-backend
            docker compose down --remove-orphans || true
            docker rm -f postgres || true
            docker compose up --build -d
